//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaringSquareApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CaringSquareEntities : DbContext
    {
        public CaringSquareEntities()
            : base("name=CaringSquareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<FriendList> FriendLists { get; set; }
        public virtual DbSet<Interest> Interests { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<POIs> POIs { get; set; }
        public virtual DbSet<PublicToilet> PublicToilets { get; set; }
        public virtual DbSet<SocialEvent> SocialEvents { get; set; }
    }
}
