//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaringSquareApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Interest
    {
        
        public int InterestId { get; set; }

        [Required]
        [DisplayName("Interest Value")]
        public string InterestName { get; set; }
        [DisplayName("User Name")]
        public string UserUserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
