//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaringSquareApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class POIs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POIs()
        {
            this.PublicToilets = new HashSet<PublicToilet>();
            this.SocialEvents = new HashSet<SocialEvent>();
        }
    
        public int PlaceId { get; set; }

        [Required]
        [DisplayName("Place Name")]
        public string Name { get; set; }

        [Required]
        [DisplayName("Theme")]
        public string Theme { get; set; }

        [Required]
        [DisplayName("Place Theme")]
        public string SubTheme { get; set; }

        [Required]
        [DisplayName("Address")]
        public string Address { get; set; }

        [Required]
        [DisplayName("Latitude")]
        public string Latitude { get; set; }

        [Required]
        [DisplayName("Longitude")]
        public string Longitude { get; set; }

        [Required]
        [DisplayName("Category ")]
        public string Category { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PublicToilet> PublicToilets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocialEvent> SocialEvents { get; set; }
    }

}
