//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaringSquareApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PublicToilet
    {
        public int ToiletId { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string FemaleStatus { get; set; }

        [Required]
        public string MaleStatus { get; set; }

        [Required]
        public string Accessibility { get; set; }

        [Required]
        public string Latitude { get; set; }

        [Required]
        public string Longitude { get; set; }
        public int POIPlaceId { get; set; }
    
        public virtual POIs POIs { get; set; }
    }
}
