//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaringSquareApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class SocialEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SocialEvent()
        {
            this.Participants = new HashSet<Participant>();
        }
    
        public int EventId { get; set; }
        [DisplayName("Event Name")]
        [Required]
        public string EventName { get; set; }
        [DisplayName("Event Date")]
        [Required]
        public string EventDate { get; set; }
        [DisplayName("Event Time")]
        [Required]
        public string EventTime { get; set; }
        [DisplayName("User Name")]
        [Required]
        public string UserUserId { get; set; }
        [DisplayName("Place Name")]
        [Required]
        public int POIPlaceId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participant> Participants { get; set; }
        public virtual POIs POIs { get; set; }
    }
}
